### ISSUE TITLE
windows defender deletes it automatically.

### ISSUE THREAD

**Issue by ilovefreesw** [uDMBK/BetterStickyNotes#1]
Windows defender is detecting it as a severe infection to the PC. It deletes the EXE file after downloading, and it doesn't even let me add it as an exception. I think the code in it needs to fixed to prevent that. Or, I don't know if you did injected the Trojan on purpose.

https://www.virustotal.com/gui/file/253d03af5b6fe377bd1e208d1fddf687d9d78a4d50daa8bb7c797c8251be47d0/detection

![image](https://user-images.githubusercontent.com/77317006/118646557-f8942780-b7fd-11eb-8a8b-5772ae1a9fd6.png)

**Comment by uDMBK** [comment]
i'll get right on it, i suspect it's because it adds itself to the startup registry automatically so i'll remove that. it could also be importing the user32.dll to allow the window to be dragged without a traditional tool bar.

these are all false positives, you can reverse the code using programs like dnSpy as the releases are not obfuscated and see that it is the same as the source code.

i'll be sure to keep you updated, if i don't get it done in the next hour i'll be asleep so give me up to 24 hours.

so sorry for this inconvenience, i ran it on another system but never thought to run it through virustotal!

**Comment by ilovefreesw** [comment]
It is not a false positive. Sure I assume it may not harm the computer but trust me no one is going to use/intall it after seeing that VT report. Thanks.

**Comment by uDMBK** [comment]
investigated this issue further,

only 0.3.0 returns the VT report you received,

[0.3.1](https://github.com/uDMBK/BetterStickyNotes/releases/tag/0.3.1) returns [2 false positives](https://www.virustotal.com/gui/file/1aa33bd21a13028b09422b9d6e85979a1521b8f6f056a0ba1429716b36f187dc/detection). you can confirm this by downloading 0.3.1 and running it through virustotal.

after removing the issue i suspected it was (registry access for startup) from 0.3.1 i [received this report](https://www.virustotal.com/gui/file/36746ff1f7483189ddbcb2402831711f084b1c75c376bf3d973446746ff54b68/detection) with only 1 false positive

i use the term 'false positive' as i am sure my software is not malicious.

after decompiling 0.3.0 i have no idea how it managed to set off 26 malicious flags, but alas 0.3.1 does not do that, 
- to elaborate further, after decompiling 0.3.0 and rebuilding it it returned [this report with 11 flags](https://www.virustotal.com/gui/file/13525b600bc16a8ebeb7a70fc0f84186a6a2b32fbb38073eb7abef1a52950cc9/detection) so like yeah they were false positives

i will release the modified version of 0.3.1 if you want as it already creates a startup shortcut and if the registry stuff is gonna set off a flag may as well remove it

**Comment by uDMBK** [comment]
and [done](https://github.com/uDMBK/BetterStickyNotes/releases/tag/0.3.1.1)

i'll go back and add virustotal reports for the rest too. just lmk if you want me to keep this issue open for now unless the issue persists.

i encourage you to [join the development discord server](https://discord.gg/7xHU5TACsz) and open a ticket there if it does persist as i can have a member of the support team discuss the issue with you whilst i am asleep

**Comment by ilovefreesw** [comment]
Okay cool. Can close it now.... thanks for the quick action :)
